# Generated by Django 3.2.5 on 2021-07-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('image', models.CharField(max_length=122)),
                ('witha', models.CharField(max_length=122)),
                ('price', models.CharField(max_length=10)),
            ],
        ),
    ]
