# Generated by Django 3.1 on 2021-11-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_auto_20210826_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=12)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rder',
            fields=[
                ('oid', models.AutoField(primary_key=True, serialize=False)),
                ('noc', models.CharField(max_length=122)),
                ('cardno', models.CharField(max_length=20)),
                ('expiry', models.CharField(max_length=20)),
                ('prod', models.CharField(max_length=50)),
                ('price', models.CharField(default='', editable=False, max_length=10)),
                ('cvv', models.CharField(max_length=4)),
                ('street', models.CharField(max_length=122)),
                ('city', models.CharField(max_length=122)),
                ('state', models.CharField(max_length=122)),
                ('zip', models.CharField(max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.CharField(default=145, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='prod',
            field=models.CharField(default=564, max_length=50),
            preserve_default=False,
        ),
    ]
