# Generated by Django 3.1 on 2021-11-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_auto_20211115_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='oid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
