# Generated by Django 3.1 on 2021-11-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0005_auto_20211116_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='oid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
